import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/cn";
import { Navbar } from "@/react/components/navbar/navbar";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Les CuicuiteDays | 13 & 14 Juin 2025",
  description: "Generated by create next app", // TODO: Update the meta description
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={cn("antialiased", poppins.variable, "h-dvh w-screen bg-background")}>
        <main className="pt-6 px-52">
          <Navbar />

          {children}
        </main>
      </body>
    </html>
  );
}
