import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../styles/globals.css";
import { cn } from "@/utils/cn";
import { Navbar } from "@/react/components/navbar/navbar";
import { Footer } from "@/react/components/footer";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Les CuicuiteDays | 13 & 14 Juin 2025",
  description: "Generated by create next app", // TODO: Update the meta description
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={cn("antialiased", poppins.className, "w-screen min-h-screen bg-layout bg-cover bg-no-repeat")}>
        <main className="pt-6 px-4 md:px-52">
          <Navbar />

          {children}
        </main>

        {/* <Footer /> */}
      </body>
    </html>
  );
}
